FROM node:20-alpine

RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -u 1001 nodejs

WORKDIR /app

COPY . .

RUN npm ci

USER nodejs

EXPOSE 4000

ENV NODE_ENV=development
ENV PORT=4000

CMD ["npm", "run", "dev"]