FROM node:20-alpine

RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -u 1001 nodejs

WORKDIR /app

COPY package.json package-lock.json* ./

RUN chown -R nodejs:nodejs .
USER nodejs
RUN npm ci

USER root
COPY . .
RUN chown -R nodejs:nodejs .
USER nodejs

EXPOSE 7001

CMD ["npm", "run", "dev", "--workspace=service-room"]
